version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_laboratorio
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: laboratoriodb
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data