name: Validar Banco de Dados (Prisma)

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  validar_banco:
    name: Validar Schema do Banco
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o codigo fonte
        uses: actions/checkout@v4

      - name: 2. Configurar o Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Instalar o Prisma localmente
        run: npm install prisma --save-dev
      
      - name: 4. Validar Formatação Estética (Prisma Format)
        run: |
          npx prisma format
          git diff --exit-code
